### ISSUE TITLE
Merge Windows branch into upstream

### ISSUE THREAD

**Issue by hbons** [serras/SparkleShare#11]
I think it's time to (finally) start merging the Windows branch into upstream. I'm really thankful for all the work you and @wimh have been doing making SparkleShare work on Windows!

Before that though, there are a few tidying up points that I think need doing:
- Move the Windows related files from / to SparkleShare/Windows/ (like tools/ and addmedia.xlst)
- Merge README.windows.md into README.md
- There's some Windows related stuff in SparkleLib/windows. Ideally I'd like SparkleLib to work without any modifications, we should see if we can merge those tweaks into SparkleLib
- Drop the use of git submodules and rely on a fixed copy instead (so new bugs or API changes don't creep in)
- Remove SmartIrc4Net references as we're now using a custom protocol over tcp
- Include the DLLs from cefsharp into SparkleShare/Windows/lib/ 

Any thoughts on the possibilities of this?

**Comment by serras** [comment]
I'll try to have a look at all of this during the weekend. However, there are some things to hack on before:
- I've seen that there's now support for invitation in SparkleShare. We should have something like that in Windows. Maybe for a first version not fully integrated in the system (I mean, that you could click on a SparkleShare link and open the invitation), but at least supported within the GUI.
- There's some SparkleLib code that only works with .NET Framework 4.0. Until now, all code was compatible with .NET 3.5, so we could use Visual Studio 2008 to compile. Maybe this is a good time to move to Visual Studio 2010.

Some of the things you mention (like removing SmartIrc4Net) have already been done, so I'm confident it won't be very difficult to have eveything working :)

**Comment by hbons** [comment]
Cool! :)
- Yes, ControllerBase.InstallProtocolHandler is the thing to override. I'm using a hack for this: a script that copies the invite.xml to ~/SparkleShare when sparkleshare:// is clicked. SparkleShare watches this folder for invites and opens a GUI when a valid one is detected.
- If there are things that can be done on 3.5 I can try to port some things back, but I'll need to know what they are.

**Comment by serras** [comment]
I'm starting to work on the port. Right now, I've spotted some issues porting SparkleLib so that there is no folder `windows` with code: that folder essentially contains code to replicate what `autotools` do with the `*.in` files. There is no easy way to do that in Windows (I mean, without installing a fully Unix-like shell in Windows).
Do you have any ideas to handle this in a platform-independent way?

**Comment by serras** [comment]
In principle, I've done most of the things required. I've made the final touches to the installer, so that msysGit is wrapped in the Windows installer and it's launched automatically. The latest commits also implement the protocol handler for sparkleshare://. And all libraries are included in the repository (no external modules).
At the end, it seems that all the code is compatible with .NET Framework 3.5.
Tell me if you need something more to be done.

**Comment by hbons** [comment]
Excellent! Thanks so much. I'll merge this in now. :)

**Comment by hbons** [comment]
Merged!

**Comment by wimh** [comment]
> Right now, I've spotted some issues porting SparkleLib so that there is no folder windows with code: that folder essentially contains code to replicate what autotools do with the *.in files. There is no easy way to do that in Windows (I mean, without installing a fully Unix-like shell in Windows).

In case it helps, I can explain the background of the choices I made. I think these were the options:
- I tried to compile it with windows ports of autotools & co. I finally gave up, partly because SparkleShare uses functionality which was not ported to windows yet. (but maybe it is much easier now).
- I could write my own tool which just supported enough to translate the .in files used in SparkleShare.
- But I finally chose to use [T4](http://tirania.org/blog/archive/2009/Mar-10.html). 

The reason was that T4 has native support both in visual studio as monodevelop. I think it fits exactly the task (ie. preprocessing of sourcecode). I also had a personal reason - it was a good opportunity for me to learn T4. I also used T4 to generate embeded resources from the various pictures. That way there were less dependencies for the finished executable.

So instead of finding another way of converting the .in files in windows, it would also be possible to start using the .tt files in linux. 

There are also .xml.in files in the [plugins](https://github.com/hbons/SparkleShare/tree/master/data/plugins) directory. In that case I thought it would be easier to use xslt to convert them into proper xml.

> Drop the use of git submodules and rely on a fixed copy instead

I'm not an expert on this, but I think this also requires you to modify the main readme to list the included modules, where they come from, and what there license is. (and don't link to my mirrors, but to the original source - I just created those mirrors to make it easier to use a git submodule, for example because the original repository was hg).

**Comment by wimh** [comment]
Oh and before I forget; well done @serras

**Comment by hbons** [comment]
can someone paste me the licenses for the DLLs (or links to them)? I'm not sure where they come from... Don't want to have the lawyers on my doorstep :)

**Comment by serras** [comment]
In `SparkleShare\Windows\Tools`:
- `TextTemplating`: MIT/X11, as can be seen in https://github.com/hbons/SparkleShare/tree/master/SparkleShare/Windows/tools/TextTemplating
- `gettext-cs-utils`: LGPL, as can be seen in https://github.com/hbons/SparkleShare/blob/master/SparkleShare/Windows/tools/gettext-cs-utils/license.lgpl.header
- `xslt` seems to have been specifically created for use in SparkleShare

In `SparkleShare\Windows\lib`:
- `CefSharp.dll` is from .NET Chromium Embedded Framework. It's BSD-licensed, as seen in https://github.com/chillitom/CefSharp
- Some code comes from Chromium Embedded Framework (http://code.google.com/p/chromiumembedded/), which is BSD-licensed
- I suppose libavformat, libavcodec and so on come from Libav (http://libav.org/), which states than can be both GPL and LGPL licensed

I hope it's all, and that it's correct. May you check it also, @wimh ?

**Comment by wimh** [comment]
It's not that there would be lawyers on your doorstep, it is more a matter of politeness. You have chosen a license for SparkleShare too, and you expect others to respect that. For example CefSharp was included in binary form without any reference to the source or license. But I guess that has been solved, as it is removed.

@serras I think your list is correct.

**Comment by hbons** [comment]
@wimh sure, i was just joking of course.
